export {default as Home} from './Home'
export {default as Store} from './Store.js'
export {default as Accessories} from './Accessories'
export {default as Brand} from './Brand'
export {default as Pages} from './Pages'
export{default as AboutUs} from './AboutUs'
export{default as News} from './News'
export{default as ContactUs} from './ContactUs'
